### ISSUE TITLE
[B] Feature_001 : Mail Service

### ISSUE THREAD

**Issue by cediar** [vscarmena/spring-base-project#1]
Product Owner asks for a feature which sends a confirmation message to a new signed up user.
It would be implemented with Spring Mail and using Thymeleaf template engines, that may include i18n messages for those confirmation emails.

The flow is as follows:
1. User sign up at the form, with an email address.
2. The app sends a confirmation email to that email address with a confirmation link.
3. When the new user clicks on that link, his/her account would be now confirmed and activated, and returns him/her to home page, as logged in.

In order to test it, Junit test would be great!

**Comment by cediar** [comment]
Concerning to email confirmation link, it could be like:
**"host.com/newuser/email/confirmation/{code}"**
where {code} might be such a generated code from user.id.

**Comment by cediar** [comment]
![f30fd24c56e1bcfc926883d6a51d5a00](https://cloud.githubusercontent.com/assets/25976626/24094925/22dc488a-0d5b-11e7-883e-c5a0f744b09c.gif)

**Comment by BigThor23** [comment]
Good job bro

**Comment by cediar** [comment]
OK. Mail Service is now available. However, @xavigc7  registration page (jsp) is needed as long as MailController needs a mapping. In addition, I would need both:
- registration-error page, and 
- registration-confirmed  page.

 In the last one, there must be something like **"Your registration is complete!. Please checkout your email inbox in order to verify your account."**

Thank you in advanced, pals!
